### ISSUE TITLE
Return of ismember_rows depends on version

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#123]
There seems to be a rounding issue or something of the sort in the simple_version=False implementation.
Probably lines 157 and 158, where the matrices are converted to int64 type voids.

a = np.array([[0. , 1. , 1. , 0. , 0.2, 0.8, 0.5, 0.5, 0.5],
                      [0. , 0. , 1. , 1. , 0.5, 0.5, 0.8, 0.2, 0.5]])
b = np.array([[0, 1, 1, 0],
                      [0, 0, 1, 1]])

ismember_rows(a, b, sort=False)
(array([ True,  True,  True,  True,  True,  True,  True,  True,  True]), array([0, 1, 2, 3, 0, 0, 0, 0, 0]))

ismember_rows(a, b, sort=False, simple_version=True)
(array([ True,  True,  True,  True, False, False, False, False, False]), array([0, 1, 2, 3]))

**Comment by keileg** [comment]
The problem was probably related to a tacit assumption that the data was int, without this being specified.

I have made a new implementation, to be pushed, which utilizes np.unique's row-wise option (introduced in np version 1.13). This seems to fix the problem, and provides a much less opaque implementation.

**Comment by keileg** [comment]
Resolved in #124
