### ISSUE TITLE
Avoid numba compilation during import

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1233]
We have some functions that are compiled by `numba` during import, see for instance [utilities](https://github.com/pmgbergen/porepy/blob/31654ffd1c1de609bd138a2b6061051af6236816/src/porepy/compositional/utils.py) in the compositional flow branch. Note also the contrast to other numba calls that are not exposed during import, for instance [here](https://github.com/pmgbergen/porepy/blob/31654ffd1c1de609bd138a2b6061051af6236816/src/porepy/utils/setmembership.py#L197). 

Compiling significantly slows import and is a drag on development, particularly during testing. We should therefore explore if it is possible to refactor the code so that the functions are only compiled upon invocation.

**Comment by vlipovac** [comment]
To summarize today's discussion and ideas during the User meeting:

- For now, issue is primarily related to running individual tests or scripts during development (running same code multiple times after minor changes), not so much on the overall performance of the import in "deployed" use (running a working example)
- primary culprit is porepy.compositional.utils.py, with un-scoped usage of numba functionality, i.e. execution/compilation in each import (if for some reason the caching does not work like in the test suite. Since coming mergers will add the flash f.e., more culprits will require a more general solution.
- disabling numba JIT via an environmental flag is of limited use because of nested, compiled functions and the usage of numba.vectorize and numba.guvectorize (ufunc dispatchers) (the compilation of those I was not able to disable so far, maybe someone finds something)
- ufunc dispatchers can be avoided by implementing the parallel solution yourself, but that will add a serious amount of tricky code
- temporary solution is to remove the import of troubling modules in the __init__, but with increasing package complexity (multiple modules in different subpackages use imports -> transitive performance downgrade) this is clearly only temporary
- another solution is a proper package set-up with ahead-of-time compilation and storage of compiled modules in some format. That depends on numba's development, which is behind our ambitions let's say.

So unfortunately, more problems than solutions.
It may take some time to fix this properly, and until then and until all of the coming mergers with lots of numba usage are integrated, it might be helpful to go for the temporary solution.
I will try to find out more until the next user meeting.

**Comment by keileg** [comment]
Thanks for the write-up, @vlipovac

**Comment by isakhammer** [comment]
**Side note:** 

The optimization level NUMBA_OPT can be adjusted, and may affect the compilation time: "_In some cases this may increase performance, in other cases it may impede performance, the same can be said for compilation time._". 

See doc https://numba.readthedocs.io/en/stable/reference/envvars.html#envvar-NUMBA_OPT

**Comment by vlipovac** [comment]
@keileg Could you please give an example of your usage where you notice the excessive time?
Did you observe this on your machine or on GH?

I tested the caching hypothesis, but it turned out that the cache is not invalidated between test runs.
Also, I ran some of the tests (params) multiple times, with and without import of `compositional` in `porepy.__init__` and I could not observe an increase when the compiled functions are included.

I am running the porepy docker image, i.e. the very first run of any test is indeed much longer due to compilation, but not the successive ones.

**Comment by keileg** [comment]
On a reasonably fast desktop, running `distances/test_distances.py` (where the tests themselves take very little time) takes 25s when I force numba recompilation, and then 10s on subsequent calls. When I comment out all lines involving numba-calls in `compositional/utils.py`, the runtime is consistently below 8s.

Granted, the 2s difference is not huge (though it is quite a bit more on my poor old laptop), but as we add more numba directives, it will not go down. Of course the real cost comes when the waiting time is so long one ends up doing something else in between.
