### ISSUE TITLE
Bug in refine_grid_1d

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#1277]
The grid produced by refine_grid_1d has only ones as its cell_face matrix. The implementation of the function must be improved and tests should be added.

**Comment by keileg** [comment]
- [ ] Fix the implementation of `cell_faces`
- [ ] Improve tests
- [ ] Consider reimplementing the rather opaque definition of the new nodes


The tests should not only check node coordinates, but also the sanity of the resulting grid; including checking `cell_faces`. Also, we should have a grid with a duplicated node, replicating the case of intersecting 1d fractures in a 2d medium.

**Comment by keileg** [comment]
@jhabriel You may be interested in following this one. I hope to do this within a few working days.

**Comment by keileg** [comment]
Mainly notes to self: It turns out (for technical reasons that I will not try to document here) that in the current implementation, the definition of new nodes is not only opaque, but probably wrong even in simple cases where the nodes and cells are ordered linearly (say, indices of both nodes and cells increasing with x-coordinate). For general grids with permuted indices, the implementation is far off and new concepts must be introduced. 

Though it is not clear to me how relevant the case with permuted indices is in practice, I find it hard to define an algorithm that has a reasonable range of validity without uncertainty in whether there are relevant edge cases that are not covered. I will therefore try to aim for a general implementation and hope I can make it work.
