### ISSUE TITLE
Right or left hand rule?

### ISSUE THREAD

**Issue by wmboon** [pmgbergen/porepy#235]
https://github.com/pmgbergen/porepy/blob/fac31d60c24371e22feb3eae9e2ee3f400a24e19/src/porepy/grids/grid.py#L54-L61

The comment is contradictory. 
Right hand rule (the convention) would imply that nodes are ordered clockwise as seen from the cell with outward pointing normal vector. So which is it?

**Comment by keileg** [comment]
Good question. I don't think anyone has thought about this code after it stopped making trouble, that is, after we correctly translated the corresponding functions from mrst.

My understanding is that when I do the right hand rule on the order of the face-nodes, I get a normal vector pointing inwards; I think you can translate this to cw or ccw more correctly than me. 

To be specific, see pp.grids.simplex.py, L230-236, and L278-305: The face-node relation is defined in a certain order, but first the nodes of the individual tets may be permuted. I did a quick drawing, and found that with points p_0 = (0, 0, 0,), p_1 = (1, 0, 0), p_2 = (0, 1, 0), p_3 = (0, 0, 1), a correct ordering of the cell-node relation is (p_1, p_0, p_2, p_3) [so that if we pass in the natural (p0, p1, p2, p3), the first two are permuted]. Inserting this tet into L234-6, I get the inwards normal. 

Does this make sense? I can update the documentation when we have converged, but I don't trust my judgement on matters of geometry.

**Comment by wmboon** [comment]
Thanks for the prompt reply. Following your example, I also expect inward normal vectors on all faces in accordance with the right-hand rule. In my understanding, cell_faces then becomes a column of -1 for this tetrahedron. 

I'm not able to verify this at the moment (sorry) but if it's true, then it would be good to swap the +1 and -1 in the code documentation referenced above.
