### ISSUE TITLE
fix documentation in assembler

### ISSUE THREAD

**Issue by haakon-e** [pmgbergen/porepy#380]
# Overview
A particular method in the assembler seems to have outdated documentation. The code below describes values that are returned, however nothing is returned by this method. Some values are set to the assembler however. Since these are important to understand, it could be useful to describe them in more detail instead.
https://github.com/pmgbergen/porepy/blob/7cf45ce3fd0b8467e3ff489b02241230d2c09772/src/porepy/numerics/mixed_dim/assembler.py#L737-L746

**Comment by keileg** [comment]
I will try to take a general look at the documentation of the assembler in connection with #379.

Generally speaking, documenting this class is in part difficult, since the possibilities in setting up multi-physics systems are so many. Thus parts of the documentation will necessarily be patchy. That said, the current case, and others, clearly can and will be improved.

**Comment by keileg** [comment]
Resolved by #379
