### ISSUE TITLE
porepy grid structure

### ISSUE THREAD

**Issue by MiniSkull** [pmgbergen/porepy#431]
Hi!
I still have one question about the porepy grid structure.
Sorry for asking a question again.
Using gb = network.mesh(mesh_args), a GridBucket is created.
The GridBucket is a mixed-dimensional mesh including fracture mesh (2d) and matrix mesh (3d).
Using for g, d in gb,  I can access matrix cells and fracture cells, respectively.
For each fracture cell, its neighbor cells should have two (?) matrix cells besides several fracture cells.
Now, I want to get neighbor matrix cells as well as fracture cells for each fracture cell. 
I can get neighbor fracture cells for each fracture cell easily based on comments and advice from a previous post. But, I do not know how to get neighbor matrix cells for each fracture cell.
I want to know neighbor matrix cell ids for each fracture cell . 
It seems that it's easy for porepy to do it. However, I checked porepy for a long time but still have no idea how to do it. 

Thanks!
Best regards,
Jin

**Comment by keileg** [comment]
You will need to go via the mortar grid, which is stored in the data dictionary of the edges in the grid bucket. To get hold of a specific edge may require some boilerplate, you may want to look for loops over gb.edges() at various points in the code. Once you have it

mg = d[`mortar_grid`]

Now you can use projections in the mortar grid to map between different grids, see the methods of mg for details.

So that it is mentioned: As you will see, the code is very much based on operating on arrays of cell and face variables, etc. This applies also to the projection operators in the mortar grid. Thus jumping between individual cells will be slow if you do this extensively.

**Comment by MiniSkull** [comment]
> You will need to go via the mortar grid, which is stored in the data dictionary of the edges in the grid bucket. To get hold of a specific edge may require some boilerplate, you may want to look for loops over gb.edges() at various points in the code. Once you have it
> mg = d[mortar_grid]
> Now you can use projections in the mortar grid to map between different grids, see the methods of mg for details.
> So that it is mentioned: As you will see, the code is very much based on operating on arrays of cell and face variables, etc. This applies also to the projection operators in the mortar grid. Thus jumping between individual cells will be slow if you do this extensively.

Thanks so much for your reply.
After many days' struggle, 
I finally used following scripts to get what  I want:

for e, d in gb.edges():
gl, gh = gb.nodes_of_edge(e)
mg = d['mortar_grid']
mg.mortar_to_slave_int() * mg.master_to_mortar_int() * np.abs(gh.cell_faces)

Thanks again.
Jin
