### ISSUE TITLE
weights in match_grids.py

### ISSUE THREAD

**Issue by enricoballini** [pmgbergen/porepy#615]
Hi, I want to project a function defined in a old (coarse) grid into a new (fine) grid. To accomplish this task correctly, I had to change the line 138 of the function match_2d in match_grids.py:
original:
`weights /= old_g.cell_volumes[old_g_ind]`
modified:
`weights /= new_g.cell_volumes[new_g_ind]`

here is the code to reproduce the problem:
```
import porepy as pp
import scipy as sp
import numpy as np

domain = {"xmin": -0.5, "xmax": 0.5, "ymin": -0.5, "ymax": 0.5}
network_2d = pp.FractureNetwork2d(None, None, domain)

# new grid:
mesh_args = {"mesh_size_bound": 0.04,
        "mesh_size_frac": 0.04,
        "mesh_size_min": 0.04}
new_gb = network_2d.mesh(mesh_args)
new_g = new_gb.grids_of_dimension(2)[0]

# old_grid:
mesh_args = {"mesh_size_bound": 0.5,
    "mesh_size_frac": 0.5,
    "mesh_size_min": 0.5}
old_gb = network_2d.mesh(mesh_args)
old_g = old_gb.grids_of_dimension(2)[0]

# function definition:
fn = old_g.cell_centers[0] 
pp.plot_grid(old_g, cell_value=fn) 

# function projection:
tol = 1e-6
weights, new_g_ind, old_g_ind = pp.match_grids.match_2d(new_g, old_g, tol)
shape = (new_g.num_cells, old_g.num_cells)
mapping_matrix = sp.sparse.csr_matrix((weights, (new_g_ind, old_g_ind)), shape=shape).todense()
projected_fn = np.array( np.dot(mapping_matrix, fn) )[0]
pp.plot_grid(new_g, cell_value=projected_fn) 
```

**Comment by keileg** [comment]
I think you're right, and I also think there is a similar issue in the corresponding 1d function, although I'll have to verify that. Moreover, I'll take the oportunity to do some maintenance on the file while I'm at it.

Thanks a lot @enricoballini; this is code that is not much used, so it's great to find these issue. Do you want to make a first PR with your fix, so that you get the credit? Then I will likely add more changes before merging. Or, if you don't bother, I can take care of everything and credit you in the documentation.
