### ISSUE TITLE
map_geometry.project_plane_matrix produces nan

### ISSUE THREAD

**Issue by wmboon** [pmgbergen/porepy#623]
Hi, I tried to set check_planar to False (the 2D fractures are always planar in my case) but the projection matrix frequently becomes filled with NaN. It seems more stable with check_planar = True but I could not see what influence the check has on the computation.

MWE:
```
import numpy as np
import porepy as pp

p = np.array([[0, 0.9], [0.5, 0.5]])
e = np.array([[0], [1]])

domain = {"xmin": 0, "xmax": 1, "ymin": 0, "ymax": 1}
network_2d = pp.FractureNetwork2d(p, e, domain)
mesh_args = {'mesh_size_frac': 1, 'mesh_size_min': 1./20}

gb = network_2d.mesh(mesh_args)
grid = gb.get_grids()[0]

R = pp.map_geometry.project_plane_matrix(grid.nodes, check_planar=False)
print(R) # Should be identity but returns nan
```

**Comment by keileg** [comment]
Thanks for the feedback @wmboon. My initial comment is that if you look at 2d geometries, you should use the function `project_line_matrix`, rather than `project_plane_matrix`. I think that will take care of the NaNs (if not, it is clearly a bug), but as you have demonstrated, documentation must be improved.

I also see why you expect a unit mapping for point clouds already aligned with a coordinate axis. The current implemenation does not check for that; we may introduce it at some later point.

I'll try to update documentation and do some more maintenance on this module but it will take some time. Again, report back if project_line_matrix does not work for you, in that case I will try to prioritize this higher.

**Comment by wmboon** [comment]
Thank you for the quick response @keileg. 

Project_line_matrix does not resolve this issue because I'm projecting the two-dimensional fractures in a 3D setting (also in my example I'm projecting the 2D-"bulk", sorry for the confusion).

I believe the problem is as follows. A normal vector is computed according to the first three nodes of the grid and these are often co-linear if a 1D fracture/intersection is present. The check for co-linearity of these points is only done if check=True is passed to compute_normal(). Right now, the code passes [check = check_planar](https://github.com/pmgbergen/porepy/blob/3fbf800c7e41dae3fe86fc035003784c41333687/src/porepy/geometry/map_geometry.py#L208) but it seems to me that these check flags are not necessarily the same.

**Comment by keileg** [comment]
Short update, @wmboon: I'm on my way out of the cave of application writing, and hope to pick this up again next week.

**Comment by keileg** [comment]
After discussion with @wmboon, the best solution seems to be to remove the option `check `in `compute_normal`; in this way, a non-zero normal vector will be returned unless the points are co-linear.

I will try to fix this at a point in the near future.
