### ISSUE TITLE
Can you guide how we can modify the physics in the code?

### ISSUE THREAD

**Issue by L4student** [pmgbergen/porepy#65]
I was wondering if you can help guide how to change the fluid flow physics in the code. I am not an expert in numerical methods and discretizations, so I am wondering if there's an easy way to add/modify a partial differential equation describing some physical phenomenon? Thanks.

**Comment by keileg** [comment]
The code is built up so that it is easy to couple discretizations of different terms. For you, the most relevant model is probably the linear advection-diffusion equation, or perhaps a slightly compressible pressure equation. If you stay with these terms, you can modify parameters, such as compressibility, viscosity etc. Currently, we don't support, say temperature dependent viscosity and similar, but you can tweak this in a time loop. Improvements are planned here, but not within the first month or two.

If you want go to more advanced physics, for instance multiphase flow, this is not supported, and will not be for the foreseeable future. The main focus of the code is for now to handle complex fracture geometries, and study discretization schemes for mixed-dimensional problems.

**Comment by L4student** [comment]
Thanks. Can you point me to the code you suggested can be modified?

**Comment by keileg** [comment]
You probably want to confer the tutorial on slightly compressible flow. The
corresponding module for advection diffusion is porepy.numerics.parabolic.

tor. 9. nov. 2017 kl. 15:55 skrev L4student <notifications@github.com>:

**Comment by L4student** [comment]
Thanks.
