### ISSUE TITLE
1d Fracture class

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#659]
For consistency with 2d fractures, a 1d Fracture class is needed. In the first instance, the class will be a relatively thin wrapper around the numpy array defining its two end points.

**Comment by vlipovac** [comment]
Hei,

I have pushed a first draft for the abstract base class for the fractures and refactored the code respectively.
I have also used that opportunity to split the code across files in a more clear way.

During the refactoring, following inconsistency was found:
The EllipticFracture class (now EllipticFracture3d) overrides the parent class constructor without calling it using super.
Their signatures are completely different.
Also, when using the `copy` method (currently inherited by Fracture3d), an instance of different type is returned.
Due to the substantially different signature, the copy method can not be abstracted into the new ABC.

**Comment by jhabriel** [comment]
I left a few minor comments on commit 395d2af
